/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Buff</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.AttributeBuff#getTarget <em>Target</em>}</li>
 *   <li>{@link mdsd.rPG.AttributeBuff#getLocal <em>Local</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getAttributeBuff()
 * @model
 * @generated
 */
public interface AttributeBuff extends EObject
{
  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference list.
   * The list contents are of type {@link mdsd.rPG.Target}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference list.
   * @see mdsd.rPG.RPGPackage#getAttributeBuff_Target()
   * @model containment="true"
   * @generated
   */
  EList<Target> getTarget();

  /**
   * Returns the value of the '<em><b>Local</b></em>' containment reference list.
   * The list contents are of type {@link mdsd.rPG.LocalTarget}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Local</em>' containment reference list.
   * @see mdsd.rPG.RPGPackage#getAttributeBuff_Local()
   * @model containment="true"
   * @generated
   */
  EList<LocalTarget> getLocal();

} // AttributeBuff
