/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute Values</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.AttributeValues#getLTypes <em>LTypes</em>}</li>
 *   <li>{@link mdsd.rPG.AttributeValues#getValue <em>Value</em>}</li>
 *   <li>{@link mdsd.rPG.AttributeValues#getRule <em>Rule</em>}</li>
 *   <li>{@link mdsd.rPG.AttributeValues#getRequire <em>Require</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getAttributeValues()
 * @model
 * @generated
 */
public interface AttributeValues extends EObject
{
  /**
   * Returns the value of the '<em><b>LTypes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>LTypes</em>' attribute.
   * @see #setLTypes(String)
   * @see mdsd.rPG.RPGPackage#getAttributeValues_LTypes()
   * @model
   * @generated
   */
  String getLTypes();

  /**
   * Sets the value of the '{@link mdsd.rPG.AttributeValues#getLTypes <em>LTypes</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>LTypes</em>' attribute.
   * @see #getLTypes()
   * @generated
   */
  void setLTypes(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(AtomicNumber)
   * @see mdsd.rPG.RPGPackage#getAttributeValues_Value()
   * @model containment="true"
   * @generated
   */
  AtomicNumber getValue();

  /**
   * Sets the value of the '{@link mdsd.rPG.AttributeValues#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(AtomicNumber value);

  /**
   * Returns the value of the '<em><b>Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' containment reference.
   * @see #setRule(Rule)
   * @see mdsd.rPG.RPGPackage#getAttributeValues_Rule()
   * @model containment="true"
   * @generated
   */
  Rule getRule();

  /**
   * Sets the value of the '{@link mdsd.rPG.AttributeValues#getRule <em>Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule</em>' containment reference.
   * @see #getRule()
   * @generated
   */
  void setRule(Rule value);

  /**
   * Returns the value of the '<em><b>Require</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Require</em>' containment reference.
   * @see #setRequire(Require)
   * @see mdsd.rPG.RPGPackage#getAttributeValues_Require()
   * @model containment="true"
   * @generated
   */
  Require getRequire();

  /**
   * Sets the value of the '{@link mdsd.rPG.AttributeValues#getRequire <em>Require</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Require</em>' containment reference.
   * @see #getRequire()
   * @generated
   */
  void setRequire(Require value);

} // AttributeValues
