/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Buff</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.Buff#getRule <em>Rule</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getBuff()
 * @model
 * @generated
 */
public interface Buff extends Effect
{
  /**
   * Returns the value of the '<em><b>Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' containment reference.
   * @see #setRule(RuleB)
   * @see mdsd.rPG.RPGPackage#getBuff_Rule()
   * @model containment="true"
   * @generated
   */
  RuleB getRule();

  /**
   * Sets the value of the '{@link mdsd.rPG.Buff#getRule <em>Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule</em>' containment reference.
   * @see #getRule()
   * @generated
   */
  void setRule(RuleB value);

} // Buff
