/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Effect</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.Effect#getRule <em>Rule</em>}</li>
 *   <li>{@link mdsd.rPG.Effect#getMoveRule <em>Move Rule</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getEffect()
 * @model
 * @generated
 */
public interface Effect extends EObject
{
  /**
   * Returns the value of the '<em><b>Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rule</em>' containment reference.
   * @see #setRule(Rule)
   * @see mdsd.rPG.RPGPackage#getEffect_Rule()
   * @model containment="true"
   * @generated
   */
  Rule getRule();

  /**
   * Sets the value of the '{@link mdsd.rPG.Effect#getRule <em>Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Rule</em>' containment reference.
   * @see #getRule()
   * @generated
   */
  void setRule(Rule value);

  /**
   * Returns the value of the '<em><b>Move Rule</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Move Rule</em>' containment reference.
   * @see #setMoveRule(MoveRule)
   * @see mdsd.rPG.RPGPackage#getEffect_MoveRule()
   * @model containment="true"
   * @generated
   */
  MoveRule getMoveRule();

  /**
   * Sets the value of the '{@link mdsd.rPG.Effect#getMoveRule <em>Move Rule</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Move Rule</em>' containment reference.
   * @see #getMoveRule()
   * @generated
   */
  void setMoveRule(MoveRule value);

} // Effect
