/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entity Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdsd.rPG.RPGPackage#getEntityAttribute()
 * @model
 * @generated
 */
public interface EntityAttribute extends EObject
{
} // EntityAttribute
