/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move Attributes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.MoveAttributes#getAttribute <em>Attribute</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getMoveAttributes()
 * @model
 * @generated
 */
public interface MoveAttributes extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' containment reference list.
   * The list contents are of type {@link mdsd.rPG.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' containment reference list.
   * @see mdsd.rPG.RPGPackage#getMoveAttributes_Attribute()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttribute();

} // MoveAttributes
