/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.Move#getName <em>Name</em>}</li>
 *   <li>{@link mdsd.rPG.Move#getEType <em>EType</em>}</li>
 *   <li>{@link mdsd.rPG.Move#getPower <em>Power</em>}</li>
 *   <li>{@link mdsd.rPG.Move#getAtt <em>Att</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getMove()
 * @model
 * @generated
 */
public interface Move extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see mdsd.rPG.RPGPackage#getMove_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link mdsd.rPG.Move#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>EType</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>EType</em>' containment reference.
   * @see #setEType(EType)
   * @see mdsd.rPG.RPGPackage#getMove_EType()
   * @model containment="true"
   * @generated
   */
  EType getEType();

  /**
   * Sets the value of the '{@link mdsd.rPG.Move#getEType <em>EType</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>EType</em>' containment reference.
   * @see #getEType()
   * @generated
   */
  void setEType(EType value);

  /**
   * Returns the value of the '<em><b>Power</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Power</em>' containment reference.
   * @see #setPower(Power)
   * @see mdsd.rPG.RPGPackage#getMove_Power()
   * @model containment="true"
   * @generated
   */
  Power getPower();

  /**
   * Sets the value of the '{@link mdsd.rPG.Move#getPower <em>Power</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Power</em>' containment reference.
   * @see #getPower()
   * @generated
   */
  void setPower(Power value);

  /**
   * Returns the value of the '<em><b>Att</b></em>' containment reference list.
   * The list contents are of type {@link mdsd.rPG.AltAttribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Att</em>' containment reference list.
   * @see mdsd.rPG.RPGPackage#getMove_Att()
   * @model containment="true"
   * @generated
   */
  EList<AltAttribute> getAtt();

} // Move
