/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mult</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdsd.rPG.RPGPackage#getMult()
 * @model
 * @generated
 */
public interface Mult extends Proposition
{
} // Mult
