/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Require</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see mdsd.rPG.RPGPackage#getRequire()
 * @model
 * @generated
 */
public interface Require extends Teams
{
} // Require
