/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule B</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.RuleB#getOr <em>Or</em>}</li>
 *   <li>{@link mdsd.rPG.RuleB#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getRuleB()
 * @model
 * @generated
 */
public interface RuleB extends EObject
{
  /**
   * Returns the value of the '<em><b>Or</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Or</em>' containment reference.
   * @see #setOr(Proposition)
   * @see mdsd.rPG.RPGPackage#getRuleB_Or()
   * @model containment="true"
   * @generated
   */
  Proposition getOr();

  /**
   * Sets the value of the '{@link mdsd.rPG.RuleB#getOr <em>Or</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Or</em>' containment reference.
   * @see #getOr()
   * @generated
   */
  void setOr(Proposition value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' containment reference list.
   * The list contents are of type {@link mdsd.rPG.Target}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' containment reference list.
   * @see mdsd.rPG.RPGPackage#getRuleB_Target()
   * @model containment="true"
   * @generated
   */
  EList<Target> getTarget();

} // RuleB
