/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Self Targeting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.SelfTargeting#getZelf <em>Zelf</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getSelfTargeting()
 * @model
 * @generated
 */
public interface SelfTargeting extends EObject
{
  /**
   * Returns the value of the '<em><b>Zelf</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Zelf</em>' attribute.
   * @see #setZelf(String)
   * @see mdsd.rPG.RPGPackage#getSelfTargeting_Zelf()
   * @model
   * @generated
   */
  String getZelf();

  /**
   * Sets the value of the '{@link mdsd.rPG.SelfTargeting#getZelf <em>Zelf</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Zelf</em>' attribute.
   * @see #getZelf()
   * @generated
   */
  void setZelf(String value);

} // SelfTargeting
