/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Speed</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.Speed#getSpeedValue <em>Speed Value</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getSpeed()
 * @model
 * @generated
 */
public interface Speed extends Declaration
{
  /**
   * Returns the value of the '<em><b>Speed Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Speed Value</em>' reference.
   * @see #setSpeedValue(Attribute)
   * @see mdsd.rPG.RPGPackage#getSpeed_SpeedValue()
   * @model
   * @generated
   */
  Attribute getSpeedValue();

  /**
   * Sets the value of the '{@link mdsd.rPG.Speed#getSpeedValue <em>Speed Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Speed Value</em>' reference.
   * @see #getSpeedValue()
   * @generated
   */
  void setSpeedValue(Attribute value);

} // Speed
