/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Team Size</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.TeamSize#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see mdsd.rPG.RPGPackage#getTeamSize()
 * @model
 * @generated
 */
public interface TeamSize extends EObject
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see mdsd.rPG.RPGPackage#getTeamSize_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link mdsd.rPG.TeamSize#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

} // TeamSize
