/**
 * generated by Xtext 2.21.0
 */
package mdsd.rPG.impl;

import java.util.Collection;

import mdsd.rPG.AttributeBuff;
import mdsd.rPG.LocalTarget;
import mdsd.rPG.RPGPackage;
import mdsd.rPG.Target;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Attribute Buff</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link mdsd.rPG.impl.AttributeBuffImpl#getTarget <em>Target</em>}</li>
 *   <li>{@link mdsd.rPG.impl.AttributeBuffImpl#getLocal <em>Local</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AttributeBuffImpl extends MinimalEObjectImpl.Container implements AttributeBuff
{
  /**
   * The cached value of the '{@link #getTarget() <em>Target</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTarget()
   * @generated
   * @ordered
   */
  protected EList<Target> target;

  /**
   * The cached value of the '{@link #getLocal() <em>Local</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLocal()
   * @generated
   * @ordered
   */
  protected EList<LocalTarget> local;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AttributeBuffImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return RPGPackage.Literals.ATTRIBUTE_BUFF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Target> getTarget()
  {
    if (target == null)
    {
      target = new EObjectContainmentEList<Target>(Target.class, this, RPGPackage.ATTRIBUTE_BUFF__TARGET);
    }
    return target;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<LocalTarget> getLocal()
  {
    if (local == null)
    {
      local = new EObjectContainmentEList<LocalTarget>(LocalTarget.class, this, RPGPackage.ATTRIBUTE_BUFF__LOCAL);
    }
    return local;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case RPGPackage.ATTRIBUTE_BUFF__TARGET:
        return ((InternalEList<?>)getTarget()).basicRemove(otherEnd, msgs);
      case RPGPackage.ATTRIBUTE_BUFF__LOCAL:
        return ((InternalEList<?>)getLocal()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case RPGPackage.ATTRIBUTE_BUFF__TARGET:
        return getTarget();
      case RPGPackage.ATTRIBUTE_BUFF__LOCAL:
        return getLocal();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case RPGPackage.ATTRIBUTE_BUFF__TARGET:
        getTarget().clear();
        getTarget().addAll((Collection<? extends Target>)newValue);
        return;
      case RPGPackage.ATTRIBUTE_BUFF__LOCAL:
        getLocal().clear();
        getLocal().addAll((Collection<? extends LocalTarget>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case RPGPackage.ATTRIBUTE_BUFF__TARGET:
        getTarget().clear();
        return;
      case RPGPackage.ATTRIBUTE_BUFF__LOCAL:
        getLocal().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case RPGPackage.ATTRIBUTE_BUFF__TARGET:
        return target != null && !target.isEmpty();
      case RPGPackage.ATTRIBUTE_BUFF__LOCAL:
        return local != null && !local.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AttributeBuffImpl
