/*
 * generated by Xtext 2.21.0
 */
package mdsd.serializer;

import com.google.inject.Inject;
import java.util.List;
import mdsd.services.RPGGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AlternativeAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class RPGSyntacticSequencer extends AbstractSyntacticSequencer {

	protected RPGGrammarAccess grammarAccess;
	protected AbstractElementAlias match_AtomicAttribute_SelfTargetingParserRuleCall_1_0_q;
	protected AbstractElementAlias match_Require_RequireKeyword_0_0_q;
	protected AbstractElementAlias match_Require_Rule___IfKeyword_0_or_RequireKeyword_0_0__q;
	protected AbstractElementAlias match_Rule_SelfTargetingParserRuleCall_3_0_q;
	protected AbstractElementAlias match_Statement_LeftParenthesisKeyword_1_0_a;
	protected AbstractElementAlias match_Statement_LeftParenthesisKeyword_1_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (RPGGrammarAccess) access;
		match_AtomicAttribute_SelfTargetingParserRuleCall_1_0_q = new TokenAlias(false, true, grammarAccess.getAtomicAttributeAccess().getSelfTargetingParserRuleCall_1_0());
		match_Require_RequireKeyword_0_0_q = new TokenAlias(false, true, grammarAccess.getRequireAccess().getRequireKeyword_0_0());
		match_Require_Rule___IfKeyword_0_or_RequireKeyword_0_0__q = new AlternativeAlias(false, true, new TokenAlias(false, false, grammarAccess.getRequireAccess().getRequireKeyword_0_0()), new TokenAlias(false, false, grammarAccess.getRuleAccess().getIfKeyword_0()));
		match_Rule_SelfTargetingParserRuleCall_3_0_q = new TokenAlias(false, true, grammarAccess.getRuleAccess().getSelfTargetingParserRuleCall_3_0());
		match_Statement_LeftParenthesisKeyword_1_0_a = new TokenAlias(true, true, grammarAccess.getStatementAccess().getLeftParenthesisKeyword_1_0());
		match_Statement_LeftParenthesisKeyword_1_0_p = new TokenAlias(true, false, grammarAccess.getStatementAccess().getLeftParenthesisKeyword_1_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getSelfTargetingRule())
			return getSelfTargetingToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * SelfTargeting:
	 * 	'self.'
	 * ;
	 */
	protected String getSelfTargetingToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "self.";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_AtomicAttribute_SelfTargetingParserRuleCall_1_0_q.equals(syntax))
				emit_AtomicAttribute_SelfTargetingParserRuleCall_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Require_RequireKeyword_0_0_q.equals(syntax))
				emit_Require_RequireKeyword_0_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Require_Rule___IfKeyword_0_or_RequireKeyword_0_0__q.equals(syntax))
				emit_Require_Rule___IfKeyword_0_or_RequireKeyword_0_0__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Rule_SelfTargetingParserRuleCall_3_0_q.equals(syntax))
				emit_Rule_SelfTargetingParserRuleCall_3_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Statement_LeftParenthesisKeyword_1_0_a.equals(syntax))
				emit_Statement_LeftParenthesisKeyword_1_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Statement_LeftParenthesisKeyword_1_0_p.equals(syntax))
				emit_Statement_LeftParenthesisKeyword_1_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     SelfTargeting?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) attribute=[Attribute|ID]
	 */
	protected void emit_AtomicAttribute_SelfTargetingParserRuleCall_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'require'?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'teams' (ambiguity) '('* left=Sum
	 *     (rule start) 'teams' (ambiguity) '('* type=[Type|ID]
	 *     (rule start) 'teams' (ambiguity) '('* {And.left=}
	 *     (rule start) 'teams' (ambiguity) '('* {Or.left=}
	 *     (rule start) (ambiguity) '('* left=Sum
	 *     (rule start) (ambiguity) '('* type=[Type|ID]
	 *     (rule start) (ambiguity) '('* {And.left=}
	 *     (rule start) (ambiguity) '('* {Or.left=}
	 */
	protected void emit_Require_RequireKeyword_0_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('if' | 'require')?
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '('* left=Sum
	 *     (rule start) (ambiguity) '('* type=[Type|ID]
	 *     (rule start) (ambiguity) '('* {And.left=}
	 *     (rule start) (ambiguity) '('* {Or.left=}
	 */
	protected void emit_Require_Rule___IfKeyword_0_or_RequireKeyword_0_0__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     SelfTargeting?
	 *
	 * This ambiguous syntax occurs at:
	 *     change+=Sum (ambiguity) attritbuteToSet+=[Attribute|ID]
	 *     right=ANDcondition 'then' (ambiguity) attritbuteToSet+=[Attribute|ID]
	 *     right=Statement 'then' (ambiguity) attritbuteToSet+=[Attribute|ID]
	 *     right=Sum 'then' (ambiguity) attritbuteToSet+=[Attribute|ID]
	 *     type=[Type|ID] 'then' (ambiguity) attritbuteToSet+=[Attribute|ID]
	 */
	protected void emit_Rule_SelfTargetingParserRuleCall_3_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) 'effect' 'if' (ambiguity) left=Sum
	 *     (rule start) 'effect' 'if' (ambiguity) type=[Type|ID]
	 *     (rule start) 'effect' 'if' (ambiguity) {And.left=}
	 *     (rule start) 'effect' 'if' (ambiguity) {Or.left=}
	 *     (rule start) 'if' (ambiguity) left=Sum
	 *     (rule start) 'if' (ambiguity) type=[Type|ID]
	 *     (rule start) 'if' (ambiguity) {And.left=}
	 *     (rule start) 'if' (ambiguity) {Or.left=}
	 *     (rule start) 'require'? (ambiguity) left=Sum
	 *     (rule start) 'require'? (ambiguity) type=[Type|ID]
	 *     (rule start) 'require'? (ambiguity) {And.left=}
	 *     (rule start) 'require'? (ambiguity) {Or.left=}
	 *     (rule start) 'teams' 'require'? (ambiguity) left=Sum
	 *     (rule start) 'teams' 'require'? (ambiguity) type=[Type|ID]
	 *     (rule start) 'teams' 'require'? (ambiguity) {And.left=}
	 *     (rule start) 'teams' 'require'? (ambiguity) {Or.left=}
	 *     (rule start) ('if' | 'require')? (ambiguity) left=Sum
	 *     (rule start) ('if' | 'require')? (ambiguity) type=[Type|ID]
	 *     (rule start) ('if' | 'require')? (ambiguity) {And.left=}
	 *     (rule start) ('if' | 'require')? (ambiguity) {Or.left=}
	 *     (rule start) (ambiguity) left=Sum
	 *     (rule start) (ambiguity) type=[Type|ID]
	 *     (rule start) (ambiguity) {And.left=}
	 *     (rule start) (ambiguity) {Or.left=}
	 */
	protected void emit_Statement_LeftParenthesisKeyword_1_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {And.left=}
	 *     (rule start) (ambiguity) {Or.left=}
	 */
	protected void emit_Statement_LeftParenthesisKeyword_1_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
